import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]


def friendly(n: str) -> str:
    s = n[3:] if n.startswith("BP_") else n
    s = re.sub(r"_(Common|Elite|Nightmare)_C$", "", s)
    s = s.replace("_", " ").strip()
    return s[:96] if s else n


def boss_type(n: str) -> str:
    for p in ("GhostKing", "Lich", "Cyclops", "SkeletonWarlord", "CaveTroll"):
        if p in n:
            return "Boss"
    return "NPC"


def main() -> None:
    lines = (ROOT / "mob_candidates.txt").read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    out.append("// <auto-generated from UEDumper ClassesInfo.json — tiered mob BP_*_Common/_Elite/_Nightmare>")
    out.append("using System;")
    out.append("using System.Collections.Generic;")
    out.append("using static DMAW_DND.Enums;")
    out.append("")
    out.append("namespace DMAW_DND")
    out.append("{")
    out.append("    internal static class MobSpawnTable")
    out.append("    {")
    out.append(
        "        public static Dictionary<string, EntityManager.ActorInfo> Entries { get; } = "
        "new Dictionary<string, EntityManager.ActorInfo>(StringComparer.Ordinal)"
    )
    out.append("        {")
    for name in lines:
        name = name.strip()
        if not name:
            continue
        t = boss_type(name)
        fn = friendly(name).replace('"', "'")
        out.append(f'            {{ "{name}", new EntityManager.ActorInfo("{fn}", ActorType.{t}) }},')
    out.append("        };")
    out.append("    }")
    out.append("}")
    target = ROOT / "Source" / "Classes" / "MobSpawnTable.cs"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target} ({len(lines)} entries)")


if __name__ == "__main__":
    main()
